export const EVENTS: { [key: string]: string } = {
  GENERATION_START: "GENERATION_START",
  GENERATION_PROGRESS: "GENERATION_PROGRESS",
  GENERATION_COMPLETE: "GENERATION_COMPLETE",
  GENERATION_FAILED: "GENERATION_FAILED",
};
