export const EVENTS = {
  GENERATION_START: "GENERATION_START",
  GENERATION_PROGRESS: "GENERATION_PROGRESS",
  GENERATION_COMPLETE: "GENERATION_COMPLETE",
  GENERATION_FAILED: "GENERATION_FAILED",
} as const;
